name: pro_kit_snackbar
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/anim/

