name: pro_kit_snackbar
description: "ProKitSnackBar is a customizable and dynamic Flutter widget for displaying various types of snack bars"
version: 0.0.4
homepage: https://github.com/MRauf07/pro-kit-snackbar.git

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/anim/
    - assets/icons/

